#ifndef TAROT_TOKEN_H
#define TAROT_TOKEN_H

#include "defines.h"
#include "datatypes/value.h"
#include "system/iostream.h"

/**
 *
 */
enum tarot_token_kind {
	/* Blocks/Sections */
	TAROT_TOK_EOF,
	TAROT_TOK_COMMENT,
	TAROT_TOK_TEXTBLOCK,
/* Keywords */
	TAROT_KEYWORD_START,
	TAROT_TOK_AND,
	TAROT_TOK_AS,
	TAROT_TOK_ASSERT,
	TAROT_TOK_CATCH,
	TAROT_TOK_CLASS,
	TAROT_TOK_CONSTANT,
	TAROT_TOK_DEFINE_TYPE,
	TAROT_TOK_ELSE,
	TAROT_TOK_ENUMERATION,
	TAROT_TOK_FALSE,
	TAROT_TOK_FOR,
	TAROT_TOK_FROM,
	TAROT_TOK_FOREIGN_FUNCTION,
	TAROT_TOK_FUNCTION,
	TAROT_TOK_IF,
	TAROT_TOK_IMPORT,
	TAROT_TOK_IN,
	TAROT_TOK_IS,
	TAROT_TOK_MATCH,
	TAROT_TOK_MOD,
	TAROT_TOK_NAMESPACE,
	TAROT_TOK_NOT,
	TAROT_TOK_OPERATOR,
	TAROT_TOK_OR,
	TAROT_TOK_ALIAS,
	TAROT_TOK_PRIVATE,
	TAROT_TOK_PUBLIC,
	TAROT_TOK_RAISE,
	TAROT_TOK_RETURN,
	TAROT_TOK_SELF,
	TAROT_TOK_SWITCH,
	TAROT_TOK_TRUE,
	TAROT_TOK_TRY,
	TAROT_TOK_UNION,
	TAROT_TOK_LET,
	TAROT_TOK_WHILE,
	TAROT_TOK_XOR,
	TAROT_KEYWORD_END,
/* Operators */
	TAROT_TOK_PLUS,
	TAROT_TOK_MINUS,
	TAROT_TOK_MULTIPLY,
	TAROT_TOK_DIVIDE,
	TAROT_TOK_ASSIGN,
	TAROT_TOK_ASSIGN_ADD,
	TAROT_TOK_ASSIGN_SUB,
	TAROT_TOK_ASSIGN_MUL,
	TAROT_TOK_ASSIGN_DIV,
	TAROT_TOK_POWER,
	TAROT_TOK_GREATER_THAN,
	TAROT_TOK_LESS_THAN,
	TAROT_TOK_GREATER_EQUAL,
	TAROT_TOK_LESS_EQUAL,
	TAROT_TOK_EQUAL,
	TAROT_TOK_NOT_EQUAL,
/* Seperators and punctuators */
	TAROT_TOK_OPEN_BRACKET,
	TAROT_TOK_CLOSE_BRACKET,
	TAROT_TOK_OPEN_CURLY_BRACKET,
	TAROT_TOK_CLOSE_CURLY_BRACKET,
	TAROT_TOK_OPEN_ANGULAR_BRACKET,
	TAROT_TOK_CLOSE_ANGULAR_BRACKET,
	TAROT_TOK_COMMA,
	TAROT_TOK_COLON,
	TAROT_TOK_SEMICOLON,
	TAROT_TOK_DOT,
	TAROT_TOK_ARROW,
/* Literals */
	TAROT_TOK_STRING,
	TAROT_TOK_FSTRING,
	TAROT_TOK_RSTRING,
	TAROT_TOK_INTEGER,
	TAROT_TOK_SHORT,
	TAROT_TOK_FLOAT,
	TAROT_TOK_RATIONAL,
	TAROT_TOK_BOOLEAN,
	TAROT_TOK_IDENTIFIER
};

/**
 *
 */
extern const char* tarot_token_string(enum tarot_token_kind kind);

/**
 *
 */
extern const char* tarot_token_class(enum tarot_token_kind kind);

/**
 *
 */
struct tarot_token {
	union tarot_value value;
	struct tarot_stream_position position;
	enum tarot_token_kind kind;
};

/**
 *
 */
extern void tarot_clear_token(struct tarot_token *token);

#endif /* TAROT_TOKEN_H */
